### PR TITLE
WIP: feature/consoleBuildNg

### PR DESCRIPTION
**Pull request by MarcelDiessner**
#51 
Needs cloneRepository for successful testing

### CODE REVIEW

**Comment by TheMarcy** [comment]
Currently buildNg will always compile in the folder dist, because of the usage of 'ng build --output-path dist' and the will ignore the outputPath in angular.json, because assertion will always look for dist. Alternatively, i would need to get the outputPath key from angular.json to control successful compilation. Which way would be better? @GuentherJulian

**Comment by GuentherJulian16** [comment]
> Currently buildNg will always compile to the folder dist, because of the usage of 'ng build --output-path dist' and will ignore the outputPath in angular.json, because the assertion will always look for dist directory. Alternatively, i would need to get the outputPath key from angular.json to control successful compilation. Which way would be better? @GuentherJulian

We can pass the output folder as a second optional parameter. If the user pass the paramter to the function we can simply check in the assertion if this directory exists. If no output parameter is given then we use the normal output path specified in the angular.json file. Is there a simple way to extract this path from the file?

**Comment by GuentherJulian** [comment]
> Currently buildNg will always compile to the folder dist, because of the usage of 'ng build --output-path dist' and will ignore the outputPath in angular.json, because the assertion will always look for dist directory. Alternatively, i would need to get the outputPath key from angular.json to control successful compilation. Which way would be better? @GuentherJulian

We can pass the output folder as a second optional parameter. If the user pass the paramter to the function we can simply check in the assertion if this directory exists. If no output parameter is given then we use the normal output path specified in the angular.json file. Is there a simple way to extract this path from the file?

**Comment by MarcelDiessner** [comment]
Currently I'm not able to find out why the ng build command is executed succesfully in linux pipeline but not on windows.

**Review by GuentherJulian — APPROVED** [review]

**Pull request merged**
